### ISSUE TITLE
Is it possible to provide an example combined with vscode?

### ISSUE THREAD

**Issue by wangluochao902** [yeger00/pylspclient#11]
Hi, Thanks for this helpful library. It is a nice job.

But I am still a little bit lost when I tried to develop a new vscode extension using your library. Is it possible to provide an example like this https://github.com/openlawlibrary/pygls/tree/master/examples/json-extension?  It will be much easier to get started.
Thanks in advance.

**Comment by yeger00** [comment]
Hi,
Can you please elaborate what you trying to achieve?
This library is currently a python implementation of client side (like visual studio code) not server side (as I understand like pygls).

 I do want to expand the library to support both sides (but didn't get to do it yet).

Please feel free to contribute, even by opening more issues.

Thanks
