### ISSUE TITLE
Three definition functions in LspClient

### ISSUE THREAD

**Issue by smathot** [yeger00/pylspclient#18]
LspClient has three functions that rely on the `textDocument/definition` method. Two (slightly different) functions are called `definition()`, and one is called `typeDefinition()` and it is identical to the first `definition()` function. I don't fully understand yet what these functions are supposed to do, but this strikes me as incorrect :-)

**Comment by yeger00** [comment]
I took some time, but it is fixed here: https://github.com/yeger00/pylspclient/pull/37

Thanks!
