### ISSUE TITLE
Add Pydantic

### ISSUE THREAD

**Issue by yeger00** [yeger00/pylspclient#35]
Change the structs to use the  [pydantic](https://github.com/pydantic/pydantic) library.

**Comment by eadaradhiraj** [comment]
Kindly check and review https://github.com/yeger00/pylspclient/pull/38

**Comment by yeger00** [comment]
Really cool. Thanks for you help @eadaradhiraj I will look at it thoroughly tonight.

**Comment by yeger00** [comment]
Done in:
https://github.com/yeger00/pylspclient/pull/40
https://github.com/yeger00/pylspclient/pull/42
https://github.com/yeger00/pylspclient/pull/47
https://github.com/yeger00/pylspclient/pull/48
